name: raizen_obd
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_reactive_ble: ^5.2.0
  flutter_svg: ^2.0.7
  geocoding: ^2.1.0
  geolocator: ^10.1.0
  google_fonts: ^5.1.0
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  intl: ^0.18.1
  permission_handler: ^10.4.3
  visibility_detector: ^0.4.0+2
  web_socket_channel: ^2.4.0
  webview_flutter: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
 image_path: "assets/icon.png"
 android: true
 ios: true

flutter:
  uses-material-design: true
  fonts:
    - family: FuturaBold
      fonts:
        - asset: fonts/FuturaBold.ttf
    - family: FuturaCondensed
      fonts:
        - asset: fonts/FuturaCondensed.otf
  assets:
     - assets/images/
